version: '3'
services:
  nvchad_cpp:
    build:
      context: .
      dockerfile: arch.Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER: ${USER}
    env_file:
      - .env
    image: josmann/nvchad_cpp_img:latest
    container_name: nvchad_cpp
    tty: true
    security_opt:
      - seccomp:unconfined # For lldb debugging
    cap_add:
      - SYS_PTRACE # For lldb debugging
    volumes:
      #- './dotfiles/custom:/home/jonas/.config/nvim/lua/custom'
      - './.config:/home/jonas/.config'
      - '/home/jonas/git:/home/jonas/git'
      - '/home/jonas/aicons:/home/jonas/aicons'
      - '/home/jonas/Docker/compose_files:/home/jonas/Docker'
